version: '3.5'

networks:
  # this will allow you to use service discovery and address a container by its name from within the network
  keycloak:

services:
  postgres:
    container_name: postgres_keycloak_database
    image: postgres:14.5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - keycloak
  keycloak:
    container_name: keycloak_authrization_server
    image: quay.io/keycloak/keycloak:19.0
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak # use container by its name
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_FEATURES: token-exchange
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - keycloak

# http://localhost:8080/auth/