ARG IMAGE_REPOSITORY=dpage/pgadmin4
ARG IMAGE_TAG=6.13

FROM ${IMAGE_REPOSITORY}:${IMAGE_TAG}
ENV PGADMIN_DEFAULT_EMAIL admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD password

# docker build -t pgadmin4-keycloak:1.0 .
# docker run -d -p 80:80 -t pgadmin4-keycloak:1.0